//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int MemberID { get; set; }
        public string MemberName { get; set; }
        public string ICNumber { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string Postcode { get; set; }
        public string ContactTitle { get; set; }
        public string ContactNumber { get; set; }
        public string EmailAddress { get; set; }
        public string Gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
