//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGenerator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SembawangSportEntities1 : DbContext
    {
        public SembawangSportEntities1()
            : base("name=SembawangSportEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking1> Booking1 { get; set; }
        public virtual DbSet<Facility1> Facility1 { get; set; }
        public virtual DbSet<Member1> Member1 { get; set; }
        public virtual DbSet<Availability1> Availability1 { get; set; }
    }
}
