//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        public int FacilityID { get; set; }
        public string FacilityType { get; set; }
        public string FacilityName { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> MaintenanceDate { get; set; }
        public int AllowedHours { get; set; }
    }
}
